const state={token:localStorage.getItem("edutrack_token"),user:null,page:"dashboard",cache:{},roleChoice:"student"};
const $=s=>document.querySelector(s);
const api=async(path,opts={})=>{
  const headers={"Content-Type":"application/json",...(opts.headers||{})};
  if(state.token) headers.Authorization=`Bearer ${state.token}`;
  const res=await fetch(path,{...opts,headers});
  if(!res.ok){let msg="Request failed";try{msg=(await res.json()).detail||msg}catch{};throw new Error(msg)}
  return res.json();
};
const initials=n=>(n||"U").split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase();
const toast=m=>{const x=document.createElement("div");x.className="toast";x.textContent=m;$("#toast-root").appendChild(x);setTimeout(()=>x.remove(),2600)};
const fmt=d=>new Date(d).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});
const escapeHtml=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pill=p=>p>=80?`<span class="pill green">${p}%</span>`:p>=75?`<span class="pill yellow">${p}%</span>`:`<span class="pill red">${p}%</span>`;
const modal=(title,body)=>{$("#modal-root").innerHTML=`<div class="modal-backdrop" id="modal"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="close" onclick="closeModal()">×</button></div>${body}</div></div>`};
const closeModal=()=>$("#modal-root").innerHTML="";
window.closeModal=closeModal;

const navConfig={
student:[["MAIN","dashboard","▦","Dashboard"],["ACADEMICS","attendance","◉","Attendance"],["","courses","▣","Courses"],["","assignments","✓","Assignments"],["","grades","◆","Grades"],["","timetable","□","Timetable"],["SERVICES","leave","↗","Leave Management"],["","announcements","◌","Announcements"],["","notifications","♢","Notifications"],["","assistant","✦","AI Assistant"],["ACCOUNT","profile","◎","Profile"]],
faculty:[["MAIN","dashboard","▦","Dashboard"],["TEACHING","students","♟","My Students"],["","attendance","◉","Attendance"],["","qr","▧","QR Attendance"],["","analytics","◒","Analytics"],["","leaves","↗","Leave Requests"],["","assignments","✓","Assignments"],["","grades","◆","Grades"],["","timetable","□","Timetable"],["COMMUNICATION","announcements","◌","Announcements"],["","reports","▤","Reports"],["","assistant","✦","AI Assistant"],["ACCOUNT","profile","◎","Profile"]],
admin:[["MAIN","dashboard","▦","Dashboard"],["MANAGEMENT","students","♟","Students"],["","faculty","♙","Faculty"],["","departments","⌂","Departments"],["","courses","▣","Courses"],["","sections","▤","Sections"],["","timetable","□","Timetable"],["ANALYTICS","analytics","◒","Analytics"],["","leaves","↗","Leave Management"],["","announcements","◌","Announcements"],["","reports","▤","Reports"],["SECURITY","users","♚","Users & Roles"],["","audit","◫","Audit Logs"],["","settings","⚙","Settings"],["","assistant","✦","AI Assistant"]]
};

function setupNav(){
  const nav=$("#nav");nav.innerHTML="";
  (navConfig[state.user.role]||[]).forEach(([section,id,icon,label])=>{
    if(section) nav.insertAdjacentHTML("beforeend",`<div class="nav-section">${section}</div>`);
    nav.insertAdjacentHTML("beforeend",`<button class="nav-item ${state.page===id?"active":""}" data-page="${id}"><span>${icon}</span>${label}</button>`);
  });
  nav.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;setupNav();renderPage();$("#sidebar").classList.remove("open")});
}
async function boot(){
  if(!state.token)return showLogin();
  try{state.user=await api("/api/me");showApp();await renderPage()}catch{state.token=null;localStorage.removeItem("edutrack_token");showLogin()}
}
function showLogin(){document.body.classList.remove("in-app");$("#login-view").classList.remove("hidden");$("#app-view").classList.add("hidden")}
function showApp(){
  $("#login-view").classList.add("hidden");$("#app-view").classList.remove("hidden");
  $("#sidebar-name").textContent=state.user.name;$("#sidebar-role").textContent=state.user.role;
  $("#sidebar-avatar").textContent=initials(state.user.name);$("#top-avatar").textContent=initials(state.user.name);setupNav();updateNotif();
}
$("#role-switch")?.addEventListener("click",()=>{});
document.querySelectorAll(".role-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".role-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.roleChoice=b.dataset.role;$("#email").value=state.roleChoice==="student"?"student@edutrack.local":state.roleChoice==="faculty"?"faculty@edutrack.local":"admin@edutrack.local";$("#password").value=state.roleChoice==="student"?"student123":state.roleChoice==="faculty"?"faculty123":"admin123"});
$("#show-password").onclick=()=>{$("#password").type=$("#password").type==="password"?"text":"password"};
$("#login-form").onsubmit=async e=>{e.preventDefault();try{const r=await api("/api/login",{method:"POST",body:JSON.stringify({email:$("#email").value,password:$("#password").value})});state.token=r.token;localStorage.setItem("edutrack_token",r.token);state.user=r.user;showApp();await renderPage()}catch(err){toast(err.message)}};
$("#logout").onclick=async()=>{try{await api("/api/logout",{method:"POST"})}catch{}state.token=null;localStorage.removeItem("edutrack_token");showLogin()};
$("#mobile-menu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
$("#notif-btn").onclick=()=>{state.page="notifications";setupNav();renderPage()};

async function renderPage(){
  const title=state.page.replace(/-/g," ");$("#page-title").textContent=title;$("#breadcrumb").textContent=`${state.user.role} / ${title}`;
  const f={dashboard:pageDashboard,attendance:pageAttendance,courses:pageCourses,assignments:pageAssignments,grades:pageGrades,timetable:pageTimetable,leave:pageLeave,leaves:pageLeave,announcements:pageAnnouncements,notifications:pageNotifications,profile:pageProfile,assistant:pageAssistant,students:pageStudents,faculty:pageFaculty,departments:pageDepartments,sections:pageSections,analytics:pageAnalytics,qr:pageQR,reports:pageReports,users:pageUsers,audit:pageAudit,settings:pageSettings};
  try{await (f[state.page]||pageDashboard)()}catch(e){$("#page").innerHTML=`<div class="card"><b>Could not load this page.</b><p class="muted">${escapeHtml(e.message)}</p></div>`}
}
async function get(k,url){return state.cache[k]||(state.cache[k]=await api(url))}
function invalidate(...keys){keys.forEach(k=>delete state.cache[k])}

async function pageDashboard(){
  const d=await api("/api/dashboard");
  if(state.user.role==="student"){
    const rows=d.courses.map(c=>`<div class="metric-row"><div><small>${escapeHtml(c.code)} · ${escapeHtml(c.name)}</small><div class="progress"><span style="width:${c.attendance}%"></span></div></div><strong>${c.attendance}%</strong></div>`).join("");
    const ass=await get("assignments","/api/assignments");const ann=await get("announcements","/api/announcements");
    $("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">STUDENT PORTAL</div><h3>Good morning, ${escapeHtml(state.user.name.split(" ")[0])} 👋</h3><p class="muted">Track attendance, academics and requests from one place.</p></div><button class="primary" onclick="state.page='leave';setupNav();renderPage()">Apply for Leave →</button></div>
    <div class="grid stats"><div class="card"><div class="stat-label">Overall Attendance</div><div class="stat-value">${d.attendance}%</div><div class="stat-sub good">Healthy status</div></div><div class="card"><div class="stat-label">CGPA</div><div class="stat-value">${d.cgpa}</div><div class="stat-sub good">Excellent</div></div><div class="card"><div class="stat-label">Courses</div><div class="stat-value">${d.courses.length}</div><div class="stat-sub muted">Enrolled</div></div><div class="card"><div class="stat-label">Classes Recorded</div><div class="stat-value">${d.total_classes}</div><div class="stat-sub muted">${d.present_classes} attended</div></div></div>
    <div class="grid two" style="margin-top:16px"><div class="card"><div class="section-head"><h3>Subject Attendance</h3><span>Current semester</span></div>${rows}</div><div class="card"><div class="section-head"><h3>Upcoming Assignments</h3><span>View all</span></div><div class="list">${ass.slice(0,3).map(a=>`<div class="list-item"><strong>${escapeHtml(a.title)}</strong><p>${escapeHtml(a.course)} · Due ${fmt(a.due_date)}</p></div>`).join("")||'<div class="empty">No assignments.</div>'}</div></div></div>
    <div class="grid two" style="margin-top:16px"><div class="card"><div class="section-head"><h3>Attendance Insight</h3></div><div class="answer">Your overall attendance is <b>${d.attendance}%</b>. ${d.attendance<75?"You are below the minimum threshold and should prioritize attendance.":"You are currently above the 75% minimum threshold."}</div></div><div class="card"><div class="section-head"><h3>Latest Announcements</h3></div><div class="list">${ann.slice(0,3).map(a=>`<div class="list-item"><strong>${escapeHtml(a.title)}</strong><p>${escapeHtml(a.message)}</p></div>`).join("")}</div></div></div>`;
  }else if(state.user.role==="faculty"){
    $("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">FACULTY PORTAL</div><h3>Good morning, ${escapeHtml(state.user.name.split(" ")[1]||state.user.name)} 👋</h3><p class="muted">Manage your classes, attendance and student performance.</p></div><button class="primary" onclick="state.page='qr';setupNav();renderPage()">Generate QR →</button></div>
    <div class="grid stats"><div class="card"><div class="stat-label">Today's Classes</div><div class="stat-value">${d.courses.length}</div></div><div class="card"><div class="stat-label">Total Students</div><div class="stat-value">${d.student_count}</div></div><div class="card"><div class="stat-label">Attendance</div><div class="stat-value">${d.attendance}%</div></div><div class="card"><div class="stat-label">Pending Leaves</div><div class="stat-value">${d.pending_leaves}</div></div></div>
    <div class="card" style="margin-top:16px"><div class="section-head"><h3>My Courses</h3><span>${d.courses.length} assigned</span></div><table><thead><tr><th>Course</th><th>Students</th><th>Actions</th></tr></thead><tbody>${d.courses.map(c=>`<tr><td><b>${escapeHtml(c.code)}</b> ${escapeHtml(c.name)}</td><td>${c.students}</td><td><button class="secondary" onclick="state.page='attendance';setupNav();renderPage()">Attendance</button></td></tr>`).join("")}</tbody></table></div>`;
  }else{
    $("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">ADMIN CONTROL CENTER</div><h3>Institution overview</h3><p class="muted">Manage people, academics, attendance, reports and system controls.</p></div><button class="primary" onclick="state.page='users';setupNav();renderPage()">Manage Users →</button></div>
    <div class="grid stats"><div class="card"><div class="stat-label">Students</div><div class="stat-value">${d.students}</div><div class="stat-sub good">Active</div></div><div class="card"><div class="stat-label">Faculty</div><div class="stat-value">${d.faculty}</div></div><div class="card"><div class="stat-label">Courses</div><div class="stat-value">${d.courses}</div></div><div class="card"><div class="stat-label">Departments</div><div class="stat-value">${d.departments}</div></div></div>
    <div class="grid two" style="margin-top:16px"><div class="card"><div class="section-head"><h3>Operational Alerts</h3></div><div class="grid three"><div><div class="stat-label">Pending Leaves</div><div class="stat-value">${d.pending_leaves}</div></div><div><div class="stat-label">At Risk</div><div class="stat-value danger">${d.at_risk}</div></div><div><div class="stat-label">Health</div><div class="stat-value good">Stable</div></div></div></div><div class="card"><div class="section-head"><h3>Quick Actions</h3></div><div class="toolbar"><button class="secondary" onclick="state.page='students';setupNav();renderPage()">Students</button><button class="secondary" onclick="state.page='courses';setupNav();renderPage()">Courses</button><button class="secondary" onclick="state.page='analytics';setupNav();renderPage()">Analytics</button><button class="secondary" onclick="state.page='settings';setupNav();renderPage()">Settings</button></div></div></div>`;
  }
}

async function pageAttendance(){
  const [summary,rows]=await Promise.all([get("summary","/api/attendance/summary"),get("attendance","/api/attendance")]);
  const own=state.user.role==="student"?summary.find(x=>x.student_id===state.user.id):null;
  const content=state.user.role==="student"?`<div class="grid two"><div class="card"><div class="section-head"><h3>Overall Attendance</h3><span>${own.overall}%</span></div><div class="stat-value">${own.overall}%</div><div class="progress" style="margin:12px 0"><span style="width:${own.overall}%"></span></div><p class="muted small">${own.present} of ${own.total} recorded classes attended.</p></div><div class="card"><div class="section-head"><h3>Attendance Calculator</h3></div><p class="muted small">Target threshold: 75%</p><div class="form-grid"><div class="form-field"><label>Conducted<input class="form-control" id="calc-total" type="number" value="${own.total}"></label></div><div class="form-field"><label>Present<input class="form-control" id="calc-present" type="number" value="${own.present}"></label></div></div><button class="primary" style="margin-top:12px" onclick="calcAttendance()">Calculate</button><div id="calc-result" class="answer">Enter your numbers to calculate.</div></div></div>
  <div class="card" style="margin-top:16px"><div class="section-head"><h3>Subject Attendance</h3><span>Current semester</span></div><table><thead><tr><th>Course</th><th>Present</th><th>Total</th><th>Attendance</th></tr></thead><tbody>${own.subjects.map(x=>`<tr><td>${escapeHtml(x.course)}</td><td>${x.present}</td><td>${x.total}</td><td>${pill(x.attendance)}</td></tr>`).join("")}</tbody></table></div>
  <div class="card" style="margin-top:16px"><div class="section-head"><h3>Attendance History</h3></div>${calendar(rows.filter(x=>x.student_id===state.user.id))}</div>`
  :`<div class="card"><div class="section-head"><h3>Attendance Overview</h3><button class="primary" onclick="openAttendanceModal()">Mark Attendance</button></div><table><thead><tr><th>Student</th><th>Overall</th><th>Subjects</th><th>Status</th></tr></thead><tbody>${summary.map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${x.overall}%</td><td>${x.subjects.map(s=>`${escapeHtml(s.course)} ${s.attendance}%`).join(" · ")}</td><td>${x.overall<75?'<span class="pill red">Critical</span>':x.overall<80?'<span class="pill yellow">Warning</span>':'<span class="pill green">Healthy</span>'}</td></tr>`).join("")}</tbody></table></div>`;
  $("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">ATTENDANCE</div><h3>Attendance management</h3><p class="muted">Monitor daily status, thresholds and attendance risk.</p></div></div>${content}`;
}
function calendar(rows){const map={};rows.forEach(r=>map[r.date]=r.status);let h='<div class="calendar">';["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].forEach(x=>h+=`<div class="cal-head">${x}</div>`);for(let i=0;i<35;i++){let d=new Date();d.setDate(d.getDate()-34+i);let key=d.toISOString().slice(0,10),st=map[key]||"none";h+=`<div class="day ${st}"><strong>${d.getDate()}</strong><div class="small">${st==="none"?"—":st}</div></div>`}return h+"</div>"}
function calcAttendance(){const total=+$("#calc-total").value,present=+$("#calc-present").value;if(total<=0)return;let miss=0;while(present/(total+miss+1)*100>=75)miss++;let need=0;while((present+need)/(total+need)*100<75&&need<100)need++;$("#calc-result").innerHTML=`You can miss approximately <b>${miss}</b> more class(es) and remain at 75%. To reach 75% now, attend approximately <b>${need}</b> consecutive class(es).`}

async function pageCourses(){const cs=await get("courses","/api/courses");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">ACADEMICS</div><h3>Courses</h3><p class="muted">View your current academic courses and assignments.</p></div>${state.user.role!=="student"?'<button class="primary" onclick="toast(\'Course creation API can be extended here.\')">+ Add Course</button>':''}</div><div class="grid three">${cs.map(c=>`<div class="card"><div class="eyebrow">${escapeHtml(c.code)}</div><h3>${escapeHtml(c.name)}</h3><p class="muted small">${escapeHtml(c.department)} · Semester ${c.semester} · ${c.credits} credits</p>${state.user.role==="student"?`<div class="metric-row"><div><small>Attendance</small><div class="progress"><span style="width:${c.attendance||0}%"></span></div></div><strong>${c.attendance||0}%</strong></div>`:""}<button class="secondary" onclick="toast('Course details opened')">View Details</button></div>`).join("")}</div>`}

async function pageAssignments(){const rows=await get("assignments","/api/assignments");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">ACADEMICS</div><h3>Assignments</h3><p class="muted">Track deadlines, submissions and grading.</p></div>${state.user.role!=="student"?'<button class="primary" onclick="assignmentModal()">+ Create Assignment</button>':''}</div><div class="card"><table><thead><tr><th>Assignment</th><th>Course</th><th>Due</th><th>Description</th><th>Action</th></tr></thead><tbody>${rows.map(a=>`<tr><td><b>${escapeHtml(a.title)}</b></td><td>${escapeHtml(a.course)}</td><td>${fmt(a.due_date)}</td><td>${escapeHtml(a.description)}</td><td>${state.user.role==="student"?'<button class="secondary" onclick="toast(\'Submission workflow ready\')">Submit</button>':'<button class="secondary" onclick="toast(\'Assignment details\')">Manage</button>'}</td></tr>`).join("")}</tbody></table></div>`}
async function assignmentModal(){const cs=await get("courses","/api/courses");modal("Create Assignment",`<form onsubmit="saveAssignment(event)"><div class="form-grid"><div class="form-field"><label>Course<select class="form-control" id="a-course">${cs.map(c=>`<option value="${c.id}">${c.code} — ${c.name}</option>`).join("")}</select></label></div><div class="form-field"><label>Due date<input class="form-control" id="a-due" type="date" required></label></div></div><div class="form-field" style="margin-top:12px"><label>Title<input class="form-control" id="a-title" required></label></div><div class="form-field" style="margin-top:12px"><label>Description<textarea class="form-control" id="a-desc" rows="4"></textarea></label></div><button class="primary" style="margin-top:14px">Create</button></form>`)}
async function saveAssignment(e){e.preventDefault();await api("/api/assignments",{method:"POST",body:JSON.stringify({course_id:+$("#a-course").value,title:$("#a-title").value,description:$("#a-desc").value,due_date:$("#a-due").value})});closeModal();invalidate("assignments");toast("Assignment created");renderPage()}

async function pageGrades(){const rows=await get("grades","/api/grades");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">ACADEMICS</div><h3>Grades</h3><p class="muted">Academic performance and course results.</p></div>${state.user.role!=="student"?'<button class="primary" onclick="gradeModal()">+ Enter Grade</button>':''}</div><div class="card"><table><thead><tr><th>Student</th><th>Course</th><th>Assignment</th><th>Midterm</th><th>Final</th><th>Letter</th></tr></thead><tbody>${rows.map(g=>`<tr><td>${escapeHtml(g.student)}</td><td>${escapeHtml(g.course)}</td><td>${g.assignment_score}</td><td>${g.midterm}</td><td>${g.final}</td><td><span class="pill green">${g.letter}</span></td></tr>`).join("")}</tbody></table></div>`}
async function gradeModal(){const [cs,users]=await Promise.all([get("courses","/api/courses"),get("users","/api/users")]);const students=users.filter(x=>x.role==="student");modal("Enter Grade",`<form onsubmit="saveGrade(event)"><div class="form-grid"><div class="form-field"><label>Student<select class="form-control" id="g-student">${students.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join("")}</select></label></div><div class="form-field"><label>Course<select class="form-control" id="g-course">${cs.map(c=>`<option value="${c.id}">${c.code}</option>`).join("")}</select></label></div><div class="form-field"><label>Assignment<input class="form-control" id="g-a" type="number" value="90"></label></div><div class="form-field"><label>Midterm<input class="form-control" id="g-m" type="number" value="85"></label></div><div class="form-field"><label>Final<input class="form-control" id="g-f" type="number" value="90"></label></div><div class="form-field"><label>Letter<input class="form-control" id="g-l" value="A"></label></div></div><button class="primary" style="margin-top:14px">Save Grade</button></form>`)}
async function saveGrade(e){e.preventDefault();await api("/api/grades",{method:"POST",body:JSON.stringify({student_id:+$("#g-student").value,course_id:+$("#g-course").value,assignment_score:+$("#g-a").value,midterm:+$("#g-m").value,final:+$("#g-f").value,letter:$("#g-l").value})});closeModal();invalidate("grades");toast("Grade saved");renderPage()}

async function pageTimetable(){const rows=await get("timetable","/api/timetable");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">SCHEDULE</div><h3>Timetable</h3><p class="muted">Classes, rooms and faculty schedule.</p></div></div><div class="grid three">${rows.map(x=>`<div class="card"><div class="eyebrow">${x.day}</div><h3>${escapeHtml(x.course)}</h3><p><b>${x.start}–${x.end}</b></p><p class="muted">Room ${escapeHtml(x.room)}</p></div>`).join("")}</div>`}

async function pageLeave(){const rows=await get("leaves","/api/leaves");const student=state.user.role==="student";$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">REQUESTS</div><h3>${student?"Leave Management":"Leave Requests"}</h3><p class="muted">${student?"Apply for leave and track approval status.":"Review and manage student leave requests."}</p></div>${student?'<button class="primary" onclick="leaveModal()">+ Apply Leave</button>':''}</div><div class="card"><table><thead><tr><th>Student</th><th>Dates</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.student)}</td><td>${fmt(r.from_date)} – ${fmt(r.to_date)}</td><td>${escapeHtml(r.reason)}</td><td><span class="pill ${r.status==="approved"?"green":r.status==="rejected"?"red":"yellow"}">${r.status}</span></td><td>${!student&&r.status==="pending"?`<button class="secondary" onclick="reviewLeave(${r.id},'approve')">Approve</button> <button class="danger-btn" onclick="reviewLeave(${r.id},'reject')">Reject</button>`:"—"}</td></tr>`).join("")}</tbody></table></div>`}
async function leaveModal(){modal("Apply for Leave",`<form onsubmit="saveLeave(event)"><div class="form-grid"><div class="form-field"><label>From<input class="form-control" id="l-from" type="date" required></label></div><div class="form-field"><label>To<input class="form-control" id="l-to" type="date" required></label></div></div><div class="form-field" style="margin-top:12px"><label>Reason<input class="form-control" id="l-reason" required placeholder="Medical appointment"></label></div><div class="form-field" style="margin-top:12px"><label>Description<textarea class="form-control" id="l-desc" rows="4"></textarea></label></div><div class="form-field" style="margin-top:12px"><label>Supporting document name<input class="form-control" id="l-doc" placeholder="medical-note.pdf"></label></div><button class="primary" style="margin-top:14px">Submit Request</button></form>`)}
async function saveLeave(e){e.preventDefault();await api("/api/leaves",{method:"POST",body:JSON.stringify({from_date:$("#l-from").value,to_date:$("#l-to").value,reason:$("#l-reason").value,description:$("#l-desc").value,document_name:$("#l-doc").value})});closeModal();invalidate("leaves");toast("Leave request submitted");renderPage()}
async function reviewLeave(id,a){await api(`/api/leaves/${id}/${a}`,{method:"POST"});invalidate("leaves","dashboard");toast(`Leave ${a}d`);renderPage()}

async function pageAnnouncements(){const rows=await get("announcements","/api/announcements");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">COMMUNICATION</div><h3>Announcements</h3><p class="muted">Stay informed about classes, departments and campus updates.</p></div>${state.user.role!=="student"?'<button class="primary" onclick="announcementModal()">+ New Announcement</button>':''}</div><div class="list">${rows.map(a=>`<div class="card"><div class="section-head"><h3>${escapeHtml(a.title)}</h3><span>${fmt(a.created_at)}</span></div><p class="muted">${escapeHtml(a.message)}</p><span class="pill gray">${escapeHtml(a.audience)}</span></div>`).join("")}</div>`}
async function announcementModal(){modal("New Announcement",`<form onsubmit="saveAnnouncement(event)"><div class="form-field"><label>Title<input class="form-control" id="n-title" required></label></div><div class="form-field" style="margin-top:12px"><label>Audience<select class="form-control" id="n-a"><option value="all">Everyone</option><option value="department">Department</option><option value="semester">Semester</option></select></label></div><div class="form-field" style="margin-top:12px"><label>Message<textarea class="form-control" id="n-msg" rows="5" required></textarea></label></div><button class="primary" style="margin-top:14px">Publish</button></form>`)}
async function saveAnnouncement(e){e.preventDefault();await api("/api/announcements",{method:"POST",body:JSON.stringify({title:$("#n-title").value,message:$("#n-msg").value,audience:$("#n-a").value})});closeModal();invalidate("announcements","notifications");toast("Announcement published");renderPage();updateNotif()}

async function pageNotifications(){const rows=await get("notifications","/api/notifications");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">INBOX</div><h3>Notifications</h3><p class="muted">Your latest academic and system notifications.</p></div></div><div class="list">${rows.map(n=>`<div class="card"><div class="section-head"><h3>${escapeHtml(n.title)}</h3><span>${fmt(n.created_at)}</span></div><p class="muted">${escapeHtml(n.message)}</p>${!n.read?`<button class="secondary" onclick="readNotif(${n.id})">Mark read</button>`:"<span class='pill green'>Read</span>"}</div>`).join("")}</div>`}
async function readNotif(id){await api(`/api/notifications/${id}/read`,{method:"POST"});invalidate("notifications");renderPage();updateNotif()}
async function updateNotif(){if(!state.token)return;try{const n=await api("/api/notifications");const unread=n.filter(x=>!x.read).length;$("#notif-count").textContent=unread;$("#notif-count").classList.toggle("hidden",!unread)}catch{}}

async function pageProfile(){const u=await api("/api/me");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">ACCOUNT</div><h3>Profile</h3><p class="muted">Your account and academic identity.</p></div></div><div class="card"><div class="grid two"><div><div class="avatar" style="width:64px;height:64px;font-size:18px">${initials(u.name)}</div><h3>${escapeHtml(u.name)}</h3><span class="pill gray">${u.role}</span></div><div class="list"><div class="list-item"><strong>Email</strong><p>${escapeHtml(u.email)}</p></div><div class="list-item"><strong>Department</strong><p>${escapeHtml(u.department||"—")}</p></div><div class="list-item"><strong>Semester / Section</strong><p>${u.semester||"—"} / ${escapeHtml(u.section||"—")}</p></div></div></div></div>`}

async function pageAssistant(){$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">SMART ASSISTANT</div><h3>EduTrack AI Assistant</h3><p class="muted">Ask questions using the information you are authorized to access.</p></div></div><div class="card"><div class="answer">Try: “What is my attendance?”, “How many classes can I miss?”, or “Which students are at risk?”</div><div class="chat" style="margin-top:14px"><input id="ai-q" placeholder="Ask EduTrack..."><button class="primary" onclick="askAI()">Ask</button></div><div id="ai-answer"></div></div>`}
async function askAI(){const q=$("#ai-q").value;if(!q)return;$("#ai-answer").innerHTML='<div class="answer">Thinking...</div>';const r=await api(`/api/ai?q=${encodeURIComponent(q)}`);$("#ai-answer").innerHTML=`<div class="answer">${escapeHtml(r.answer)}</div>`}

async function pageStudents(){const users=state.user.role==="admin"?await get("users","/api/users"):(await get("summary","/api/attendance/summary"));const rows=state.user.role==="admin"?users.filter(x=>x.role==="student"):users;$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">PEOPLE</div><h3>Students</h3><p class="muted">Student records and attendance health.</p></div>${state.user.role==="admin"?'<button class="primary" onclick="userModal(\'student\')">+ Add Student</button>':''}</div><div class="card"><table><thead><tr><th>Name</th><th>ID</th><th>Department</th><th>Attendance</th><th>Status</th></tr></thead><tbody>${rows.map(x=>{const p=x.overall??0;return `<tr><td><b>${escapeHtml(x.name)}</b></td><td>${escapeHtml(x.student_id||"—")}</td><td>${escapeHtml(x.department||"—")}</td><td>${p}%</td><td>${p<75?'<span class="pill red">At Risk</span>':'<span class="pill green">Healthy</span>'}</td></tr>`}).join("")}</tbody></table></div>`}
async function pageFaculty(){const users=await get("users","/api/users");const rows=users.filter(x=>x.role==="faculty");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">PEOPLE</div><h3>Faculty</h3><p class="muted">Faculty directory and teaching assignments.</p></div><button class="primary" onclick="userModal('faculty')">+ Add Faculty</button></div><div class="card"><table><thead><tr><th>Name</th><th>Email</th><th>Department</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${escapeHtml(x.name)}</b></td><td>${escapeHtml(x.email)}</td><td>${escapeHtml(x.department||"—")}</td><td><span class="pill ${x.active?"green":"red"}">${x.active?"Active":"Inactive"}</span></td><td><button class="secondary" onclick="toggleUser(${x.id})">${x.active?"Deactivate":"Activate"}</button></td></tr>`).join("")}</tbody></table></div>`}
async function userModal(role){modal(`Add ${role}`,`<form onsubmit="saveUser(event,'${role}')"><div class="form-grid"><div class="form-field"><label>Name<input class="form-control" id="u-name" required></label></div><div class="form-field"><label>Email<input class="form-control" id="u-email" type="email" required></label></div><div class="form-field"><label>Password<input class="form-control" id="u-pass" value="Welcome123!" required></label></div><div class="form-field"><label>Department<input class="form-control" id="u-dept" value="Computer Science"></label></div></div><button class="primary" style="margin-top:14px">Create</button></form>`)}
async function saveUser(e,role){e.preventDefault();await api("/api/users",{method:"POST",body:JSON.stringify({name:$("#u-name").value,email:$("#u-email").value,password:$("#u-pass").value,role,department:$("#u-dept").value})});closeModal();invalidate("users","dashboard");toast(`${role} created`);renderPage()}
async function toggleUser(id){await api(`/api/users/${id}/toggle`,{method:"POST"});invalidate("users","dashboard");toast("User status updated");renderPage()}

async function pageDepartments(){const rows=await get("departments","/api/departments");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">ACADEMIC STRUCTURE</div><h3>Departments</h3><p class="muted">Institutional academic units.</p></div></div><div class="grid three">${rows.map(x=>`<div class="card"><div class="eyebrow">${x.code}</div><h3>${escapeHtml(x.name)}</h3><p class="muted">Department code ${x.code}</p></div>`).join("")}</div>`}
async function pageSections(){const rows=await get("sections","/api/sections");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">ACADEMIC STRUCTURE</div><h3>Sections</h3><p class="muted">Manage semester and section organization.</p></div></div><div class="grid three">${rows.map(x=>`<div class="card"><div class="eyebrow">${escapeHtml(x.department)}</div><h3>Semester ${x.semester} · Section ${x.name}</h3><p class="muted">Capacity ${x.capacity}</p></div>`).join("")}</div>`}

async function pageAnalytics(){const rows=await get("summary","/api/attendance/summary");const dept={};rows.forEach(x=>{const st=x.name;dept[st]=x.overall});$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">ANALYTICS</div><h3>Attendance Analytics</h3><p class="muted">Identify healthy, warning and critical attendance patterns.</p></div></div><div class="grid three"><div class="card"><div class="stat-label">Healthy</div><div class="stat-value good">${rows.filter(x=>x.overall>=80).length}</div></div><div class="card"><div class="stat-label">Warning</div><div class="stat-value warn">${rows.filter(x=>x.overall>=75&&x.overall<80).length}</div></div><div class="card"><div class="stat-label">Critical</div><div class="stat-value danger">${rows.filter(x=>x.overall<75).length}</div></div></div><div class="card" style="margin-top:16px"><div class="section-head"><h3>Student Attendance Distribution</h3></div>${rows.map(x=>`<div class="metric-row"><div><small>${escapeHtml(x.name)}</small><div class="progress"><span style="width:${Math.min(x.overall,100)}%"></span></div></div><strong>${x.overall}%</strong></div>`).join("")}</div>`}

async function pageQR(){const cs=await get("courses","/api/courses");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">SMART ATTENDANCE</div><h3>QR Attendance</h3><p class="muted">Generate short-lived classroom attendance sessions.</p></div></div><div class="card"><div class="form-grid"><div class="form-field"><label>Course<select class="form-control" id="qr-course">${cs.map(c=>`<option value="${c.id}">${c.code} — ${c.name}</option>`).join("")}</select></label></div><div style="display:flex;align-items:end"><button class="primary" onclick="generateQR()">Generate Session</button></div></div><div id="qr-output" style="margin-top:18px"></div></div>`}
async function generateQR(){const r=await api(`/api/attendance/qr?course_id=${$("#qr-course").value}`,{method:"POST"});$("#qr-output").innerHTML=`<div class="qr">${escapeHtml(r.session_id)}</div><p class="muted small" style="text-align:center">Session expires in ${r.expires_in_minutes} minutes. Students scan/use this session code.</p>`}

async function pageReports(){$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">REPORTING</div><h3>Reports</h3><p class="muted">Export attendance data for analysis and administration.</p></div></div><div class="grid three"><div class="card"><h3>Attendance Report</h3><p class="muted small">Student-level attendance summary in CSV.</p><button class="primary" onclick="window.location='/api/report/attendance.csv'">Export CSV</button></div><div class="card"><h3>At-Risk Report</h3><p class="muted small">Review students below the configured threshold.</p><button class="secondary" onclick="state.page='analytics';setupNav();renderPage()">Open Analytics</button></div><div class="card"><h3>Audit Report</h3><p class="muted small">Administrative action history.</p><button class="secondary" onclick="state.page='audit';setupNav();renderPage()">Open Audit Logs</button></div></div>`}

async function pageUsers(){const rows=await get("users","/api/users");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">SECURITY</div><h3>Users & Roles</h3><p class="muted">Role-based identity and account status management.</p></div><button class="primary" onclick="userModal('student')">+ Create User</button></div><div class="card"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Department</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.email)}</td><td><span class="pill gray">${x.role}</span></td><td>${escapeHtml(x.department||"—")}</td><td>${x.active?"Active":"Inactive"}</td><td>${x.role!=="admin"?`<button class="secondary" onclick="toggleUser(${x.id})">${x.active?"Deactivate":"Activate"}</button>`:"Protected"}</td></tr>`).join("")}</tbody></table></div>`}
async function pageAudit(){const rows=await get("audit","/api/audit");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">SECURITY</div><h3>Audit Logs</h3><p class="muted">Trace important system actions and changes.</p></div></div><div class="card"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${escapeHtml(x.actor)}</td><td><span class="pill gray">${x.action}</span></td><td>${x.entity}</td><td>${escapeHtml(x.details)}</td></tr>`).join("")}</tbody></table></div>`}
async function pageSettings(){const x=await api("/api/settings");$("#page").innerHTML=`<div class="hero"><div><div class="eyebrow">SYSTEM</div><h3>Settings</h3><p class="muted">Configure attendance thresholds and QR sessions.</p></div></div><div class="card"><form onsubmit="saveSettings(event)"><div class="form-grid"><div class="form-field"><label>Minimum attendance %<input class="form-control" id="s-min" type="number" value="${x.minimum_attendance}"></label></div><div class="form-field"><label>Warning threshold %<input class="form-control" id="s-warn" type="number" value="${x.warning_threshold}"></label></div><div class="form-field"><label>Critical threshold %<input class="form-control" id="s-crit" type="number" value="${x.critical_threshold}"></label></div><div class="form-field"><label>Late after minutes<input class="form-control" id="s-late" type="number" value="${x.late_after_minutes}"></label></div><div class="form-field"><label>QR session minutes<input class="form-control" id="s-qr" type="number" value="${x.qr_session_minutes}"></label></div></div><button class="primary" style="margin-top:15px">Save Settings</button></form></div>`}
async function saveSettings(e){e.preventDefault();await api("/api/settings",{method:"PUT",body:JSON.stringify({minimum_attendance:+$("#s-min").value,warning_threshold:+$("#s-warn").value,critical_threshold:+$("#s-crit").value,late_after_minutes:+$("#s-late").value,qr_session_minutes:+$("#s-qr").value})});toast("Settings saved")}

async function openAttendanceModal(){const cs=await get("courses","/api/courses");const sum=await get("summary","/api/attendance/summary");const students=state.user.role==="faculty"?sum:sum;modal("Mark Attendance",`<form onsubmit="saveAttendance(event)"><div class="form-grid"><div class="form-field"><label>Course<select class="form-control" id="m-course">${cs.map(c=>`<option value="${c.id}">${c.code} — ${c.name}</option>`).join("")}</select></label></div><div class="form-field"><label>Date<input class="form-control" id="m-date" type="date" value="${new Date().toISOString().slice(0,10)}"></label></div><div class="form-field"><label>Student<select class="form-control" id="m-student">${students.map(x=>`<option value="${x.student_id}">${escapeHtml(x.name)}</option>`).join("")}</select></label></div><div class="form-field"><label>Status<select class="form-control" id="m-status"><option>present</option><option>absent</option><option>late</option><option>excused</option></select></label></div></div><button class="primary" style="margin-top:14px">Save Attendance</button></form>`)}
async function saveAttendance(e){e.preventDefault();await api("/api/attendance",{method:"POST",body:JSON.stringify({course_id:+$("#m-course").value,attendance_date:$("#m-date").value,student_id:+$("#m-student").value,status:$("#m-status").value})});closeModal();invalidate("attendance","summary","dashboard");toast("Attendance saved");renderPage()}

boot();
